version: '3.8'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: dev-db
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    command: -p 5432
    expose:
      - 5432
volumes:
  data:

# The purpose of this file is just to create a local postgres db as a dev environment