version: '3.6'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
    - plural-cv-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  plural-cv-db:

